title: Luca's Blog
baseurl: ""

date_format: "%Y-%m-%d"

# Build settings
kramdown:
  input: GFM
  auto_ids: true
permalink: pretty

github:
twitter:

#leave empty for disabled

disqus_shortname: #fill this in for comments
