title: Nandre's Blog
baseurl: ""

date_format: "%Y-%m-%d"
exclude: [".gitignore", "Dockerfile", "docker-compose.yml", "LICENSE", "README.md", ".gitignore"]

# Build settings
kramdown:
  input: GFM
  auto_ids: true
permalink: pretty

github: https://github.com/nan-dre
twitter: https://twitter.com/nandre42

