title: vida
baseurl: ""

date_format: "%Y-%m-%d"

# Build settings
kramdown:
  input: GFM
permalink: /:categories/:title
emptyArray: []

# Third-party services
# just leave someone empty to disable it
google_analytics:
disqus_shortname:
