title: Blog
baseurl: ""

date_format: "%Y-%m-%d"

# Build settings
kramdown:
  input: GFM
  auto_ids: true
permalink: /:categories/:title

github:
twitter:

#leave empty for disabled

disqus_shortname: luca-10
